spring.application.name=jobsapp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.web.resources.static-locations=file:///D:/jobsapp_resumes/,classpath:/static/

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=granite4:3b
spring.ai.ollama.chat.options.temperature=0.2

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.initialized=true
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.request-timeout=120s
spring.ai.mcp.client.root-change-notification=false
logging.level.org.springframework.ai=DEBUG
logging.level.io.modelcontextprotocol=DEBUG
spring.ai.mcp.client.stdio.connections.docker-gateway.command=docker
spring.ai.mcp.client.stdio.connections.docker-gateway.args[0]=mcp
spring.ai.mcp.client.stdio.connections.docker-gateway.args[1]=gateway
spring.ai.mcp.client.stdio.connections.docker-gateway.args[2]=run
logging.level.org.springframework.ai.ollama=TRACE
logging.level.org.springframework.ai.ollama.api=TRACE
logging.level.org.springframework.web.client=TRACE
logging.level.org.springframework.http.client=TRACE

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


chroma.cv-collection=${CHROMA_CV_COLLECTION:276cad80-943a-4266-bb62-2f7a099ec0c6}
chroma.job-req-collection=${CHROMA_JOB_REQ_COLLECTION:c1164efa-3bfe-4ab8-a8f3-edd70a74a486}
chroma.collections-url=${CHROMA_COLLECTIONS_URL:http://localhost:8000/api/v1/collections}
ollama.embeddings-url=${OLLAMA_EMBEDDINGS_URL:http://localhost:11434/api/embeddings}
ollama.generate-url=${OLLAMA_GENERATE_URL:http://localhost:11434/api/generate}
aws.s3.bucket=${AWS_S3_BUCKET:jobsapp-resumes}
aws.s3.region=${AWS_REGION:eu-central-1}
file.upload-temp-dir=${UPLOAD_TEMP_DIR:/tmp/jobsapp_resumes}


services.ai.base-url=http://localhost:8081